baseURL = 'https://bysniper.win/'
languageCode = 'zh-cn'
title = 'Personal Site of bysniper'
theme = "devise"

relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = "&copy; Copyright 2021, bysniper"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = -100
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    title = "Categories"
    url = "/categories/"
    weight = -90

# Configuration Features
[params]
  description = "blog of bysniper"      # Your meta description of the site
  header_title = "bysniper"                 # Your header title
  header_subtitle = "锦瑟无端五十弦，一弦一柱思华年" # Your header subtitle
  home_image = "/images/avatar.png"          # Path to header image starting from the static directory
  recent_posts = 5                           # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
    href = "http://github.com/print248"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-weibo fa-1x"
    href = "https://weibo.com/whoishandsome"
  [[params.social]]
    fa_icon = "fab fa-instagram fa-1x"
    href = "http://instagram.com/zhatianzenganiu"
  [[params.social]]
    fa_icon = "fas fa-at fa-1x"
    href = "mailto:admin@bysniper.win"

